LANGUAGES = {
    "en": "🌍 English",
    "am": "🇪🇹 Amharic",
    "om": "🇪🇹 Afaan Oromo",
    "ti": "🇪🇹 Tigrigna",
    "ar": "🌍 Arabic",
    "fr": "🌍 French",
    "es": "🌍 Spanish",
    "sw": "🌍 Swahili",
    "hi": "🌍 Hindi",
    "pt": "🌍 Portuguese",
}

STRINGS = {
    "en": {
        "welcome":          "👋 Welcome! Here is your APK file. Enjoy!",
        "join_prompt":      "🔐 To use referral & other features, please join our channel first.",
        "join_btn":         "📢 Join Channel",
        "joined_confirm":   "✅ You have joined! All features are now unlocked.",
        "not_joined":       "❌ You haven't joined yet. Please join the channel to continue.",
        "check_join_btn":   "✅ I Joined",
        "main_menu":        "🏠 Main Menu",
        "referral_menu":    "💰 My Referral",
        "balance":          "💵 Balance: {balance} ETB",
        "referrals_count":  "👥 Referrals: {count}",
        "referral_link":    "🔗 Your referral link:\n{link}",
        "share_text":       "📤 Share this link to earn 40 ETB per referral!",
        "submit_screenshot":"📸 Submit Screenshot",
        "screenshot_prompt":"📸 Send your installation screenshot now. It will be reviewed by admin.",
        "screenshot_sent":  "✅ Screenshot submitted! Admin will review shortly.",
        "withdraw_btn":     "💸 Request Payout",
        "withdraw_prompt":  "💸 Enter your Telebirr/CBE number to request payout:",
        "withdraw_min":     "❌ Minimum withdrawal is 400 ETB (10 referrals).",
        "withdraw_sent":    "✅ Payout request submitted! Admin will process it.",
        "lang_select":      "🌍 Select your language:",
        "group_welcome":    "👋 Welcome {name}! Tap below to get the app.",
        "get_app_btn":      "📦 Get the App",
        "apk_caption":      "📦 Installation video below 👇",
        "new_version":      "🆕 New update: v{version}\n📝 {changelog}\n📦 Size: {size}",
    "my_stats":         "My Stats",
    "leaderboard":      "🏆 Leaderboard",
    },
    "am": {
        "welcome":          "👋 እንኳን ደህና መጡ! የAPK ፋይልዎ እዚህ አለ። ይደሰቱ!",
        "join_prompt":      "🔐 የሪፈራል እና ሌሎች ባህሪያትን ለመጠቀም እባክዎ መጀመሪያ ቻናላችንን ይቀላቀሉ።",
        "join_btn":         "📢 ቻናሉን ይቀላቀሉ",
        "joined_confirm":   "✅ ተቀላቅለዋል! ሁሉም ባህሪያት ተከፍተዋል።",
        "not_joined":       "❌ እስካሁን አልተቀላቀሉም። ለመቀጠል ቻናሉን ይቀላቀሉ።",
        "check_join_btn":   "✅ ተቀላቅያለሁ",
        "main_menu":        "🏠 ዋና ምናሌ",
        "referral_menu":    "💰 የእኔ ሪፈራል",
        "balance":          "💵 ሂሳብ: {balance} ብር",
        "referrals_count":  "👥 ሪፈራሎች: {count}",
        "referral_link":    "🔗 የሪፈራል አገናኝዎ:\n{link}",
        "share_text":       "📤 በእያንዳንዱ ሪፈራል 40 ብር ለማግኘት ይህንን አገናኝ ያጋሩ!",
        "submit_screenshot":"📸 ስክሪንሾት ያስገቡ",
        "screenshot_prompt":"📸 የጭነት ስክሪንሾትዎን አሁን ይላኩ። በአስተዳዳሪ ይገመገማል።",
        "screenshot_sent":  "✅ ስክሪንሾት ተልኳል! አስተዳዳሪ በቅርቡ ይገመግማል።",
        "withdraw_btn":     "💸 ክፍያ ይጠይቁ",
        "withdraw_prompt":  "💸 የTelebirr/CBE ቁጥርዎን ያስገቡ:",
        "withdraw_min":     "❌ አነስተኛ ክፍያ 400 ብር (10 ሪፈራሎች) ነው።",
        "withdraw_sent":    "✅ የክፍያ ጥያቄ ተልኳል! አስተዳዳሪ ያስተናግዳል።",
        "lang_select":      "🌍 ቋንቋዎን ይምረጡ:",
        "group_welcome":    "👋 እንኳን ደህና መጡ {name}! አፕሊኬሽኑን ለማግኘት ይጫኑ።",
        "get_app_btn":      "📦 አፕሊኬሽኑን ያግኙ",
        "apk_caption":      "📦 የጭነት ቪዲዮ ከታች 👇",
        "new_version":      "🆕 አዲስ ዝማኔ: v{version}\n📝 {changelog}\n📦 መጠን: {size}",
    },
    "om": {
        "welcome":          "👋 Baga nagaan dhuftan! Faayilii APK keessan as jira. Gammadaa!",
        "join_prompt":      "🔐 Eeruu fi meeshaalee biroo fayyadamuuf, maaloo jalqaba channel keenya makaati.",
        "join_btn":         "📢 Channel Makami",
        "joined_confirm":   "✅ Makamtanii jirtu! Meeshaaleen hundi banameera.",
        "not_joined":       "❌ Ammallee hin makamne. Itti fuufuuf channel makami.",
        "check_join_btn":   "✅ Makamee jira",
        "main_menu":        "🏠 Menu Ijoo",
        "referral_menu":    "💰 Eeruu Koo",
        "balance":          "💵 Herrega: {balance} ETB",
        "referrals_count":  "👥 Eeruuwwan: {count}",
        "referral_link":    "🔗 Link eeruu keessan:\n{link}",
        "share_text":       "📤 Eeruu tokkoof ETB 40 argachuuf link kana qoodaa!",
        "submit_screenshot":"📸 Screenshot Ergi",
        "screenshot_prompt":"📸 Screenshot fe'umsaa keessan amma ergaa. Admin ilaala.",
        "screenshot_sent":  "✅ Screenshot ergameera! Admin daddaffiin ilaala.",
        "withdraw_btn":     "💸 Kaffaltti Gaafadhu",
        "withdraw_prompt":  "💸 Lakkoofsa Telebirr/CBE keessan galchi:",
        "withdraw_min":     "❌ Kaffaltti xiqqaa ETB 400 (eeruuwwan 10) dha.",
        "withdraw_sent":    "✅ Gaaffiin kaffalttii ergameera! Admin raawwata.",
        "lang_select":      "🌍 Afaan keessan filadhaa:",
        "group_welcome":    "👋 Baga nagaan dhuftan {name}! App argachuuf tuqi.",
        "get_app_btn":      "📦 App Argadhu",
        "apk_caption":      "📦 Viidiyoo fe'umsaa gadi 👇",
        "new_version":      "🆕 Haaromsa haaraa: v{version}\n📝 {changelog}\n📦 Guddina: {size}",
    "my_stats":         "የእኔ ስታቲስቲክስ",
    "leaderboard":      "🏆 ሊደርቦርድ",
    },
    "ti": {
        "welcome":          "👋 ብደሓን መጻእካ! ናይ APK ፋይልካ ኣብዚ ኣሎ። ተዘናጋዕ!",
        "join_prompt":      "🔐 ሪፈራልን ካልኦት ባህርያትን ንምጥቃም፡ በጃኻ ቅድም ቻናልና ተጸንበር።",
        "join_btn":         "📢 ቻናል ተጸንበር",
        "joined_confirm":   "✅ ተጸንቢርካ! ኩሎም ባህርያት ተኸፊቶም ኣለዉ።",
        "not_joined":       "❌ ገና ኣይተጸንበርካን። ንምቕጻል ቻናል ተጸንበር።",
        "check_join_btn":   "✅ ተጸንቢረ",
        "main_menu":        "🏠 ዋና ምናሌ",
        "referral_menu":    "💰 ሪፈራለይ",
        "balance":          "💵 ሂሳብ: {balance} ETB",
        "referrals_count":  "👥 ሪፈራላት: {count}",
        "referral_link":    "🔗 ናይ ሪፈራል ሊንክካ:\n{link}",
        "share_text":       "📤 ንሓደ ሪፈራል 40 ETB ንምርካብ ነዚ ሊንክ ኣካፍል!",
        "submit_screenshot":"📸 ስክሪንሾት ስደድ",
        "screenshot_prompt":"📸 ናይ ጽዓን ስክሪንሾትካ ሕጂ ስደድ። ብኣድሚን ክርአ እዩ።",
        "screenshot_sent":  "✅ ስክሪንሾት ተሰዲዱ! ኣድሚን ብቕልጡፍ ክርእዮ እዩ።",
        "withdraw_btn":     "💸 ክፍሊት ሕተት",
        "withdraw_prompt":  "💸 ናይ Telebirr/CBE ቁጽርካ ኣእቱ:",
        "withdraw_min":     "❌ ዝተሓተ ክፍሊት 400 ETB (10 ሪፈራላት) እዩ።",
        "withdraw_sent":    "✅ ሕቶ ክፍሊት ተሰዲዱ! ኣድሚን ክሰርሓሉ እዩ።",
        "lang_select":      "🌍 ቋንቋኻ ምረጽ:",
        "group_welcome":    "👋 ብደሓን መጻእካ {name}! ኣፕ ንምርካብ ጠውቕ።",
        "get_app_btn":      "📦 ኣፕ ርካብ",
        "apk_caption":      "📦 ቪዲዮ ጽዓን ኣብ ታሕቲ 👇",
        "new_version":      "🆕 ሓድሽ ዝማኔ: v{version}\n📝 {changelog}\n📦 ዓቐን: {size}",
    },
    "ar": {
        "welcome":          "👋 مرحباً! إليك ملف APK. استمتع!",
        "join_prompt":      "🔐 للاستخدام الإحالة والميزات الأخرى، يرجى الانضمام إلى قناتنا أولاً.",
        "join_btn":         "📢 انضم للقناة",
        "joined_confirm":   "✅ لقد انضممت! جميع الميزات متاحة الآن.",
        "not_joined":       "❌ لم تنضم بعد. انضم للقناة للمتابعة.",
        "check_join_btn":   "✅ انضممت",
        "main_menu":        "🏠 القائمة الرئيسية",
        "referral_menu":    "💰 إحالتي",
        "balance":          "💵 الرصيد: {balance} ETB",
        "referrals_count":  "👥 الإحالات: {count}",
        "referral_link":    "🔗 رابط الإحالة الخاص بك:\n{link}",
        "share_text":       "📤 شارك هذا الرابط لتكسب 40 ETB لكل إحالة!",
        "submit_screenshot":"📸 أرسل لقطة الشاشة",
        "screenshot_prompt":"📸 أرسل لقطة شاشة التثبيت الآن. سيراجعها المسؤول.",
        "screenshot_sent":  "✅ تم إرسال لقطة الشاشة! سيراجعها المسؤول قريباً.",
        "withdraw_btn":     "💸 طلب سحب",
        "withdraw_prompt":  "💸 أدخل رقم Binance/Telebirr/CBE الخاص بك:",
        "withdraw_min":     "❌ الحد الأدنى للسحب هو 400 ETB (10 إحالات).",
        "withdraw_sent":    "✅ تم إرسال طلب السحب! سيعالجه المسؤول.",
        "lang_select":      "🌍 اختر لغتك:",
        "group_welcome":    "👋 مرحباً {name}! اضغط للحصول على التطبيق.",
        "get_app_btn":      "📦 احصل على التطبيق",
        "apk_caption":      "📦 فيديو التثبيت أدناه 👇",
        "new_version":      "🆕 تحديث جديد: v{version}\n📝 {changelog}\n📦 الحجم: {size}",
    "my_stats":         "Miseensi Koo",
    "leaderboard":      "🏆 Caalanaa",
    },
    "fr": {
        "welcome":          "👋 Bienvenue! Voici votre fichier APK. Profitez-en!",
        "join_prompt":      "🔐 Pour utiliser le parrainage et autres fonctionnalités, rejoignez notre chaîne d'abord.",
        "join_btn":         "📢 Rejoindre la chaîne",
        "joined_confirm":   "✅ Vous avez rejoint! Toutes les fonctionnalités sont débloquées.",
        "not_joined":       "❌ Vous n'avez pas encore rejoint. Rejoignez la chaîne pour continuer.",
        "check_join_btn":   "✅ J'ai rejoint",
        "main_menu":        "🏠 Menu principal",
        "referral_menu":    "💰 Mon parrainage",
        "balance":          "💵 Solde: {balance} ETB",
        "referrals_count":  "👥 Parrainages: {count}",
        "referral_link":    "🔗 Votre lien de parrainage:\n{link}",
        "share_text":       "📤 Partagez ce lien pour gagner 40 ETB par parrainage!",
        "submit_screenshot":"📸 Envoyer la capture",
        "screenshot_prompt":"📸 Envoyez votre capture d'écran d'installation maintenant.",
        "screenshot_sent":  "✅ Capture envoyée! L'admin examinera bientôt.",
        "withdraw_btn":     "💸 Demander un paiement",
        "withdraw_prompt":  "💸 Entrez votre numéro Telebirr/CBE:",
        "withdraw_min":     "❌ Le retrait minimum est de 400 ETB (10 parrainages).",
        "withdraw_sent":    "✅ Demande de paiement envoyée! L'admin va traiter.",
        "lang_select":      "🌍 Choisissez votre langue:",
        "group_welcome":    "👋 Bienvenue {name}! Appuyez pour obtenir l'application.",
        "get_app_btn":      "📦 Obtenir l'application",
        "apk_caption":      "📦 Vidéo d'installation ci-dessous 👇",
        "new_version":      "🆕 Nouvelle mise à jour: v{version}\n📝 {changelog}\n📦 Taille: {size}",
    },
    "es": {
        "welcome":          "👋 ¡Bienvenido! Aquí está tu archivo APK. ¡Disfrútalo!",
        "join_prompt":      "🔐 Para usar el referido y otras funciones, únete primero a nuestro canal.",
        "join_btn":         "📢 Unirse al canal",
        "joined_confirm":   "✅ ¡Te has unido! Todas las funciones están desbloqueadas.",
        "not_joined":       "❌ Aún no te has unido. Únete al canal para continuar.",
        "check_join_btn":   "✅ Me uní",
        "main_menu":        "🏠 Menú principal",
        "referral_menu":    "💰 Mi referido",
        "balance":          "💵 Saldo: {balance} ETB",
        "referrals_count":  "👥 Referidos: {count}",
        "referral_link":    "🔗 Tu enlace de referido:\n{link}",
        "share_text":       "📤 ¡Comparte este enlace para ganar 40 ETB por referido!",
        "submit_screenshot":"📸 Enviar captura",
        "screenshot_prompt":"📸 Envía tu captura de pantalla de instalación ahora.",
        "screenshot_sent":  "✅ ¡Captura enviada! El admin revisará pronto.",
        "withdraw_btn":     "💸 Solicitar pago",
        "withdraw_prompt":  "💸 Ingresa tu número Telebirr/CBE:",
        "withdraw_min":     "❌ El retiro mínimo es 400 ETB (10 referidos).",
        "withdraw_sent":    "✅ ¡Solicitud de pago enviada! El admin procesará.",
        "lang_select":      "🌍 Selecciona tu idioma:",
        "group_welcome":    "👋 ¡Bienvenido {name}! Toca para obtener la app.",
        "get_app_btn":      "📦 Obtener la app",
        "apk_caption":      "📦 Video de instalación abajo 👇",
        "new_version":      "🆕 Nueva actualización: v{version}\n📝 {changelog}\n📦 Tamaño: {size}",
    "my_stats":         "ናይ ኣኔ ስታቲስቲክ",
    "leaderboard":      "🏆 ሊደርቦርድ",
    },
    "sw": {
        "welcome":          "👋 Karibu! Hapa kuna faili yako ya APK. Furahia!",
        "join_prompt":      "🔐 Kutumia rufaa na vipengele vingine, tafadhali jiunge na channel yetu kwanza.",
        "join_btn":         "📢 Jiunge na Channel",
        "joined_confirm":   "✅ Umejiunga! Vipengele vyote vimefunguliwa.",
        "not_joined":       "❌ Bado hujajiunga. Jiunge na channel kuendelea.",
        "check_join_btn":   "✅ Nimejiunga",
        "main_menu":        "🏠 Menyu Kuu",
        "referral_menu":    "💰 Rufaa Yangu",
        "balance":          "💵 Salio: {balance} ETB",
        "referrals_count":  "👥 Rufaa: {count}",
        "referral_link":    "🔗 Kiungo chako cha rufaa:\n{link}",
        "share_text":       "📤 Shiriki kiungo hiki kupata ETB 40 kwa kila rufaa!",
        "submit_screenshot":"📸 Tuma Picha ya Skrini",
        "screenshot_prompt":"📸 Tuma picha ya skrini ya usakinishaji sasa.",
        "screenshot_sent":  "✅ Picha imetumwa! Admin ataangalia hivi karibuni.",
        "withdraw_btn":     "💸 Omba Malipo",
        "withdraw_prompt":  "💸 Ingiza nambari yako ya Telebirr/CBE:",
        "withdraw_min":     "❌ Malipo ya chini ni ETB 400 (rufaa 10).",
        "withdraw_sent":    "✅ Ombi la malipo limetumwa! Admin atashughulikia.",
        "lang_select":      "🌍 Chagua lugha yako:",
        "group_welcome":    "👋 Karibu {name}! Gonga kupata app.",
        "get_app_btn":      "📦 Pata App",
        "apk_caption":      "📦 Video ya usakinishaji chini 👇",
        "new_version":      "🆕 Sasisho jipya: v{version}\n📝 {changelog}\n📦 Ukubwa: {size}",
    },
    "hi": {
        "welcome":          "👋 स्वागत है! यहाँ आपकी APK फ़ाइल है। आनंद लें!",
        "join_prompt":      "🔐 रेफरल और अन्य सुविधाओं के लिए, पहले हमारे चैनल से जुड़ें।",
        "join_btn":         "📢 चैनल जॉइन करें",
        "joined_confirm":   "✅ आप जुड़ गए! सभी सुविधाएं अनलॉक हो गई हैं।",
        "not_joined":       "❌ आप अभी तक नहीं जुड़े। जारी रखने के लिए चैनल जॉइन करें।",
        "check_join_btn":   "✅ मैं जुड़ गया",
        "main_menu":        "🏠 मुख्य मेनू",
        "referral_menu":    "💰 मेरा रेफरल",
        "balance":          "💵 बैलेंस: {balance} ETB",
        "referrals_count":  "👥 रेफरल: {count}",
        "referral_link":    "🔗 आपका रेफरल लिंक:\n{link}",
        "share_text":       "📤 प्रति रेफरल 40 ETB कमाने के लिए यह लिंक शेयर करें!",
        "submit_screenshot":"📸 स्क्रीनशॉट भेजें",
        "screenshot_prompt":"📸 अभी इंस्टॉलेशन स्क्रीनशॉट भेजें। एडमिन समीक्षा करेगा।",
        "screenshot_sent":  "✅ स्क्रीनशॉट भेजा गया! एडमिन जल्द समीक्षा करेगा।",
        "withdraw_btn":     "💸 भुगतान अनुरोध",
        "withdraw_prompt":  "💸 अपना Telebirr/CBE नंबर दर्ज करें:",
        "withdraw_min":     "❌ न्यूनतम निकासी 400 ETB (10 रेफरल) है।",
        "withdraw_sent":    "✅ भुगतान अनुरोध भेजा गया! एडमिन प्रोसेस करेगा।",
        "lang_select":      "🌍 अपनी भाषा चुनें:",
        "group_welcome":    "👋 स्वागत है {name}! ऐप पाने के लिए टैप करें।",
        "get_app_btn":      "📦 ऐप पाएं",
        "apk_caption":      "📦 नीचे इंस्टॉलेशन वीडियो 👇",
        "new_version":      "🆕 नया अपडेट: v{version}\n📝 {changelog}\n📦 आकार: {size}",
    "my_stats":         "إحصائياتي",
    "leaderboard":      "🏆 لوحة المتصدرين",
    },
    "pt": {
        "welcome":          "👋 Bem-vindo! Aqui está o seu arquivo APK. Aproveite!",
        "join_prompt":      "🔐 Para usar indicações e outros recursos, junte-se ao nosso canal primeiro.",
        "join_btn":         "📢 Entrar no Canal",
        "joined_confirm":   "✅ Você entrou! Todos os recursos estão desbloqueados.",
        "not_joined":       "❌ Você ainda não entrou. Entre no canal para continuar.",
        "check_join_btn":   "✅ Entrei",
        "main_menu":        "🏠 Menu Principal",
        "referral_menu":    "💰 Minha Indicação",
        "balance":          "💵 Saldo: {balance} ETB",
        "referrals_count":  "👥 Indicações: {count}",
        "referral_link":    "🔗 Seu link de indicação:\n{link}",
        "share_text":       "📤 Compartilhe este link para ganhar 40 ETB por indicação!",
        "submit_screenshot":"📸 Enviar Captura",
        "screenshot_prompt":"📸 Envie sua captura de tela de instalação agora.",
        "screenshot_sent":  "✅ Captura enviada! O admin revisará em breve.",
        "withdraw_btn":     "💸 Solicitar Pagamento",
        "withdraw_prompt":  "💸 Digite seu número Telebirr/CBE:",
        "withdraw_min":     "❌ O saque mínimo é 400 ETB (10 indicações).",
        "withdraw_sent":    "✅ Solicitação de pagamento enviada! O admin processará.",
        "lang_select":      "🌍 Selecione seu idioma:",
        "group_welcome":    "👋 Bem-vindo {name}! Toque para obter o app.",
        "get_app_btn":      "📦 Obter o App",
        "apk_caption":      "📦 Vídeo de instalação abaixo 👇",
        "new_version":      "🆕 Nova atualização: v{version}\n📝 {changelog}\n📦 Tamanho: {size}",
    },
}

def t(lang: str, key: str, **kwargs) -> str:
    lang = lang if lang in STRINGS else "en"
    text = STRINGS[lang].get(key, STRINGS["en"].get(key, key))
    return text.format(**kwargs) if kwargs else text
